--- # Master Playbook for Role Based Apache deployments
- hosts: webserver
  user: ansible
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: When the ROLE start
    raw: date > /home/test/startofrole.log
  roles:
  - redhat.webserver
  post_tasks:
  - name: When did the ROLE end
    raw: date > /home/test/endofrole.log