---
- hosts: webservers
  become: yes
  vars:
    target_package_name: git
    target_package_state: latest
  tasks:
  - name: install git
    yum:
      name: "{{ target_package_name }}"
      state: "{{ target_package_state }}"
