---
- hosts: webservers
  become: yes
  vars:
    target_package: git
    target_package_state: latest
  tasks:
  - name: install git
    yum:
      name: "{{ target_package }}"
      state: "{{ target_package_name }}"